name: Build and Attach to Pre-release

on:
  push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
                
      - name: Install Runtime
        shell: cmd  # Specify cmd shell
        run: |
          PowerBuilderRuntime.exe /s /f1"D:\a\PowerBuilder-AutoBuild-Sales-Example\PowerBuilder-AutoBuild-Sales-Example\PowerBuilderRuntime-setup.iss" 
          exit 0
          
      - name: Install Util
        shell: cmd  # Specify cmd shell
        run: |
          PowerBuilderUtilities.exe /s /f1"D:\a\PowerBuilder-AutoBuild-Sales-Example\PowerBuilder-AutoBuild-Sales-Example\PowerBuilderUtilities-setup.iss" 
          exit 0
        
      - name: Set SYSTEMDRIVE (Not recommended)
        shell: cmd
        run: |  
          dir "C:\Program Files (x86)\Appeon\Common\PowerBuilder" 2>nul  || echo "Appeon folder not found."
        
      - name: Set SYSTEMDRIVE (Not recommended)
        shell: cmd
        run: |  
          dir "C:\Program Files (x86)\Appeon\PowerBuilderUtilities 22.0" 2>nul  || echo "Appeon folder not found."    
           
      - name: Run PBAutoBuild210.exe
        shell: cmd  # Specify cmd shell
        run: |
          "C:\Program Files (x86)\Appeon\PowerBuilderUtilities 22.0\PBAutoBuild220.exe" /f "pb_salesdemo.json" /l "Log_PBBuild.log" /le "Log_PBError.log"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./salesdemo.exe